---
# tasks file for ansible-weave

# sudo semanage fcontext -a -t unconfined_exec_t -f f /usr/local/bin/weave
# sudo restorecon /usr/local/bin/weave

- name: Install service configuration
  template:
    src: sysconfig-weave.j2
    dest: /etc/sysconfig/weave
  notify: restart weave

- name: Install systemd service
  file:
    src: weave.service
    dest: /etc/systemd/system/weave.service
  notify: enable weave
