---
- name: Create peers
  set_fact:
    __weave_peers: "{{ [inventory_hostname] | difference(groups[weave_inventory_group]) }}"

- name: Install service configuration
  template:
    src: sysconfig-weave.j2
    dest: /etc/sysconfig/weave
  notify: restart weave

- name: Add --ipalloc-range (if set)
  set_fact:
    __weave_command: "{{ __weave_command + [ weave_ipalloc_range ] }}"
  when: weave_ipalloc_range | length > 0

- name: Install systemd service
  file:
    src: weave.service
    dest: /etc/systemd/system/weave.service
  notify: enable weave
