---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: node1
    image: geerlingguy/docker-centos7-ansible:latest
    pre_build_image: True
    command: /sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - weave
  - name: node2
    image: geerlingguy/docker-centos7-ansible:latest
    pre_build_image: True
    command: /sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - weave
provisioner:
  name: ansible
  options:
    diff: true
    v: true
  inventory:
    host_vars:
      node1:
        weave_launch_args:
          - "--name=::1"
          - "--log-level=debug"
          - "--dns-domain=\"mesh.local.\""
          - "--dns-ttl=10"
      node2:
        weave_launch_args:
          - "--name=::2"
          - "--log-level=debug"
          - "--dns-domain=\"mesh.local.\""
          - "--dns-ttl=10"
verifier:
  name: testinfra
  options:
    vvv: true
